export const cardsRecipe=[
    {
        id:'1',
        image:'/assets/3.jpg',
        name:'Noodle chicken soup',
        level:'intermediate',
        min:'25',
        kcal:'95',
        meat:'',
        rating:'5',
    },
    {
        id:'2',
        image:'/assets/3.jpg',
        name:'Salad with raw tauna',
        level:'advanced',
        min:'25',
        kcal:'95',
        meat:'',
        rating:'4',
    },
    {
        id:'3',
        image:'/assets/3.jpg',
        name:'Pasta with spinash',
        level:'beginner',
        min:'25',
        kcal:'95',
        meat:'',
        rating:'3.5',
    },
    {
        id:'4',
        image:'/assets/3.jpg',
        name:'cucumber salad',
        level:'intermediate',
        min:'25',
        kcal:'95',
        meat:'',
        rating:'4.5',
    },
    {
        id:'5',
        image:'/assets/3.jpg',
        name:'Masala toufu',
        level:'beginner',
        min:'25',
        kcal:'95',
        meat:'',
        rating:'3.5',
    },
    {
        id:'6',
        image:'/assets/3.jpg',
        name:'Noodle chicken soup',
        level:'advanced',
        min:'25',
        kcal:'95',
        meat:'',
        rating:'2',
    },
    {
        id:'7',
        image:'/assets/3.jpg',
        name:'Noodle chicken soup',
        level:'beginner',
        min:'25',
        kcal:'95',
        meat:'',
        rating:'3',
    },
    {
        id:'8',
        image:'/assets/3.jpg',
        name:'Noodle chicken soup',
        level:'intermediate',
        min:'25',
        kcal:'95',
        meat:'',
        rating:'4',
    },

]